maintainer        "Till Klampaeckel"
maintainer_email  "till@php.net"
license           "PHP License"
description       "Installs and configures PHP with fpm patch."
version           "0.2"
recipe            "php-fpm::install", "Installs PHP-fpm"
recipe            "php-fpm::prepare", "Creates prequesites like user and directories"
recipe            "php-fpm::pear", "Installs required PEAR packages"
recipe            "php-fpm::apc", "Installs APC-3.1.4 (beta)"
recipe            "php-fpm::xhprof", "Installs Facebook's xhprof"
recipe            "php-fpm::pspell", "Install the pspell extension"
supports 'ubuntu'
