# Offense count: 23
Metrics/AbcSize:
  Max: 42

# Offense count: 9
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: format, sprintf, percent
Style/FormatString:
  Exclude:
    - 'apt/providers/repository.rb'
    - 'easybib/libraries/config.rb'
    - 'prosody/recipes/storage.rb'
    - 'prosody/recipes/users.rb'
    - 'rds/recipes/backup.rb'

# Offense count: 2
Style/IfInsideElse:
  Exclude:
    - 'apt/recipes/cacher-client.rb'
    - 'easybib/libraries/easybib.rb'

# Offense count: 6
Style/ModuleFunction:
  Exclude:
    - 'easybib/libraries/config.rb'
    - 'easybib/libraries/easybib.rb'
    - 'easybib/libraries/ppa.rb'
    - 'easybib/libraries/sns.rb'
    - 'easybib/libraries/upstream.rb'
    - 'xhprof.io/libraries/xhprof.rb'

# Offense count: 2
Style/ZeroLengthPredicate:
  Exclude:
    - 'apt/recipes/cacher-client.rb'
