AllCops:
  Exclude:
    - 'apt/**/*'
    - 'ark/**/*'
    - 'build-essential/**/*'
    - 'chef_handler/**/*'
    - 'chef_handler_sns/**/*'
    - 'cron/**/*'
    - 'erlang/**/*'
    - 'fc_sandbox/**/*'
    - 'gemfiles/**/*'
    - 'logrotate/**/*'
    - 'mysql/**/*'
    - 'nodejs/**/*'
    - 'ohai/**/*'
    - 'opsworks_nodejs/**/*'
    - 'papertrail/**/*'
    - 'python/**/*'
    - 'rabbitmq/**/*'
    - 'rails/**/*'
    - 'rsyslog/**/*'
    - 'runit/**/*'
    - 'rvm/**/*'
    - 'sinopia/**/*'
    - 'supervisor/**/*'
    - 'test/**/*'
    - 'unused/**/*'
    - 'vagrant-test/**/*'
    - 'vendor/**/*'
    - 'xml/**/*'

inherit_from: .rubocop_todo.yml

Metrics/AbcSize:
  Max: 21
  Exclude:
    - 'easybib/providers/deploy_manager.rb'
    - '**/spec/*'
    - '**/tests/*'

Metrics/BlockLength:
  Max: 130

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'easybib/providers/deploy_manager.rb'

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 110

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only

Style/PredicateName:
  Exclude:
    - 'easybib/libraries/*'

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Style/FileName:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false
