AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: hash_rockets

MethodLength:
  Max: 35

CyclomaticComplexity:
  Max: 9

ParameterLists:
  Enabled: false

StringLiterals:
  Enabled: false

SpaceInsideBrackets:
  Enabled: false

# Some recipes have a valid reason to do so, see bprobe for example
RescueException:
  Enabled: false

AccessorMethodName:
  Enabled: false

# I dont want to separate port numbers with underscores.
NumericLiterals:
  Enabled: false

PredicateName:
  Enabled: false

FileName:
  Enabled: false

RedundantSelf:
  Enabled: false

inherit_from: rubocop-todo.yml 
