AllCops:
  Exclude:
    - 'ark/**/*'
    - 'build-essential/**/*'
    - 'chef_handler/**/*'
    - 'chef_handler_sns/**/*'
    - 'cron/**/*'
    - 'xml/**/*'
    - 'python/**/*'
    - 'ohai/**/*'
    - 'opsworks_nodejs/**/*'
    - 'vagrant-test/**/*'
    - 'test/**/*'
    - 'erlang/**/*'
    - 'rabbitmq/**/*'
    - 'Rakefile'
    - 'supervisor/**/*'
    - 'fc_sandbox/**/*'
    - 'vendor/**/*'
    - 'sinopia/**/*'
    - 'nodejs/**/*'
    - 'logrotate/**/*'
    - 'virtualbox/**/*'
    - 'vagrant/**/*'
    - 'vendor/**/*'
    - 'papertrail/**/*'
    - 'rails/**/*'
    - 'rsyslog/**/*'
    - 'runit/**/*'
    - 'mysql/**/*'

Style/SpaceBeforeFirstArg:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 8

Metrics/ParameterLists:
  Max: 6

Metrics/MethodLength:
  Max: 30

Metrics/LineLength:
  Max: 160

Metrics/CyclomaticComplexity:
  Max: 8

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Performance/StringReplacement:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false
inherit_from: .rubocop_todo.yml
