AllCops:
  Exclude:
    - 'Rakefile'
    - 'apt/**/*'
    - 'ark/**/*'
    - 'build-essential/**/*'
    - 'chef_handler/**/*'
    - 'chef_handler_sns/**/*'
    - 'cron/**/*'
    - 'erlang/**/*'
    - 'fc_sandbox/**/*'
    - 'logrotate/**/*'
    - 'mysql/**/*'
    - 'nodejs/**/*'
    - 'ohai/**/*'
    - 'opsworks_nodejs/**/*'
    - 'papertrail/**/*'
    - 'python/**/*'
    - 'rabbitmq/**/*'
    - 'rails/**/*'
    - 'rsyslog/**/*'
    - 'runit/**/*'
    - 'rvm/**/*'
    - 'sinopia/**/*'
    - 'supervisor/**/*'
    - 'test/**/*'
    - 'vagrant-test/**/*'
    - 'vendor/**/*'
    - 'vendor/**/*'
    - 'xml/**/*'

Metrics/AbcSize:
  Max: 41

Metrics/BlockLength:
  Max: 130

Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only

Metrics/PerceivedComplexity:
  Max: 8

Metrics/ParameterLists:
  Max: 6

Metrics/MethodLength:
  Max: 30

Metrics/LineLength:
  Max: 160

Metrics/CyclomaticComplexity:
  Max: 8

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/SpaceBeforeFirstArg:
  AllowForAlignment: true

Style/ExtraSpacing:
  ForceEqualSignAlignment: true

inherit_from: .rubocop_todo.yml
