source 'https://rubygems.org'
gem 'chef', '~>12.11.0'
gem 'rspec', '~>3.5.0'
gem 'rake'
gem 'foodcritic', '~>7.1.0'
gem 'chefspec', '~>5.1'
gem 'fauxhai'
gem 'test-kitchen', '~>1.13.2'
gem 'rubocop', '~>0.37.0'
gem 'aws-sdk', '~>1.0'
gem 'dep-selector-libgecode', '~>1.2.0'
gem 'berkshelf', '~>3.3'
gem 'kitchen-vagrant', :group => :integration
