source 'https://rubygems.org'
gem 'chef', '~>11.4.0'
gem 'rake', '~>10.1'
gem 'foodcritic', '~>3.0.0'
gem 'chefspec', '~>3.0.0'
gem 'test-kitchen', '~>1.0.0.beta.3'
gem 'rubocop', '0.19.0'
gem 'faraday', '0.8.9'
gem 'travis-artifacts', '~>0.2.2'
gem 'kitchen-vagrant', :group => :integration
