set_unless[:elasticsearch][:download] = "https://github.com/downloads/elasticsearch/elasticsearch"
set_unless[:elasticsearch][:version]  = "elasticsearch-0.17.3.tar.gz"
set_unless[:elasticsearch][:basedir]  = "/mnt/opt"
set_unless[:elasticsearch][:ebsdir]   = "/esdata"
set_unless[:elasticsearch][:cluster]  = "citationanalytics"
