name              'stack-citationapi'
maintainer        'Till Klampaeckel'
maintainer_email  'till@php.net'
license           'BSD License'
description       'CitationAPI roles'
version           '0.1'

supports 'ubuntu'

depends 'stack-easybib'
depends 'easybib-deploy'
depends 'ies'
depends 'haproxy'
depends 'memcache'
depends 'nginx-app'
depends 'nginx-lb'
depends 'php'
depends 'redis'
depends 'ohai'
