name              'scholar'
maintainer        'Till Klampaeckel'
maintainer_email  'till@php.net'
license           'BSD License'
description       'scholar roles'
version           '0.1'

supports 'ubuntu'

depends 'easybib'
depends 'nginx-app'
depends 'easybib-deploy'
depends 'php-posix'
depends 'bash'
depends 'percona'
depends 'redis'
depends 'memcache'
depends 'haproxy'
depends 'ohai'
depends 'apache-couchdb'
depends 'nodejs'
depends 'php-pdo_sqlite'
depends 'rsyslogd'
depends 'erlang-packages'
depends 'service'
depends 'ies'
