name              'academy'
maintainer        'Till Klampaeckel'
maintainer_email  'till@php.net'
license           'BSD License'
description       'academy roles'
version           '0.1'

supports 'ubuntu'

depends 'easybib'
depends 'nginx-app'
depends 'ies'
depends 'ohai'
depends 'percona'
depends 'php-pdo_sqlite'
depends 'nodejs'
depends 'avahi'
depends 'service'
depends 'php-xdebug'