name              'stack-research'
maintainer        'Till Klampaeckel'
maintainer_email  'till@php.net'
license           'BSD License'
description       'research roles'
version           '0.1'

supports 'ubuntu'

depends 'apache-solr'
depends 'composer'
depends 'easybib-deploy'
depends 'ies'
depends 'memcache'
depends 'nginx-app'
depends 'php'
depends 'php-fpm'
depends 'php-pear'
depends 'stack-easybib'
depends 'tideways'
