<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <style type="text/css">
        body {
            background:#fff;
            color:#000;
            font-family:'Helvetica Neue', arial,helvetica;
        }
        p {
            font-size:13px;
        }
        #error {
            padding-top:100px;
            width:400px;
            margin:auto;
            height:200px;
        }
        h1 {
            font-size: 20px;
            font-weight: bold;
        }
        .links a {
            padding-right: 15px;
            color: #0E65D6
         }
    </style>
    <title>EasyBib</title>
</head>
<body>
    <div id="error">
        <img src="http://cdn.easybib.com/images/easybib_logo.gif" />
        <h1>403: Request denied.</h1>
        <p>
            We're sorry. Your request has been denied.
        </p>
        <p class="links">
            <a href="http://www.easybib.com">EasyBib Homepage</a>
            <a href="http://drafts.easybib.com">EasyBib Blog</a>
            <a href="http://twitter.com/easybib">EasyBib Twitter</a>
        </p>
    </div>
</body>
</html>