name              'easybib-deploy'
maintainer        'Till Klampaeckel, Ulf Harnhammar'
maintainer_email  'till@php.net'
license           'BSD License'
description       'Deploys easybib'
version           '0.1'

supports 'ubuntu'

depends 'aptly'
depends 'bibcd'
depends 'satis'
depends 'php-fpm'
depends 'monit'
depends 'nginx-app'
depends 'easybib'
depends 'pecl-manager'
depends 'haproxy'
