name              'stack-fruitkid'
maintainer        'Till Klampaeckel'
maintainer_email  'till@php.net'
license           'BSD License'
description       'CitationAPI roles'
version           '0.1'

supports 'ubuntu'

depends 'composer'
depends 'easybib-deploy'
depends 'ies'
depends 'memcache'
depends 'nginx-app'
depends 'php'
depends 'php-fpm'
depends 'php-pear'
depends 'postfix'
depends 'tideways'
