Vagrant::Config.run do |config|
  config.vm.box = "karmic-nfs_0.3_4.1.8"

  #config.vm.boot_mode = :gui

  config.vm.network :hostonly, "33.33.33.124"

  config.vm.share_folder("v-data", "/vagrant_data", "./../")

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "./../"

    chef.add_recipe "dnsmasq"
    chef.add_recipe "dhcp3::configure"

    chef.log_level = :debug
  end
end
