Vagrant::Config.run do |config|

    config.vm.box = "precise64"
    config.vm.box_url = "http://dl.dropbox.com/u/1537815/precise64.box"

    config.vm.network :hostonly, "33.33.33.124"

    config.vbguest.auto_update = false

    config.vm.customize [
        "modifyvm", :id,
        "--name", "Vagrant Cookbook Testbox",
        "--memory", "256"
    ]

    config.vm.provision :shell, :inline => "apt-get update"

    chef.json = JSON.parse(File.read("./deploy.json"))
  end
end
