Vagrant::Config.run do |config|
  config.vm.box = "lucid-nfs_0.1_4.1.0"

  config.vm.network :hostonly, "33.33.33.124"

  config.vbguest.auto_update = true

    config.vm.customize [
        "modifyvm", :id,
        "--name", "Vagrant Cookbook Testbox",
        "--memory", "256"
    ]

  config.vm.provision :shell, :path => "./update-mirrors.sh"

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "./../"

    #chef.add_recipe "vagrant-fix"
    chef.add_recipe "deploy::ssl"

    this_dir   = File.dirname(__FILE__)
    deploy_ssl = JSON.parse(File.read(this_dir + "/deploy-ssl.json"))

    # add certificate and key to the json
    deploy_ssl["deploy"]["ssl"]["ssl_certificate"]     = File.read(this_dir + "/ssl/vagrant.crt")
    deploy_ssl["deploy"]["ssl"]["ssl_certificate_key"] = File.read(this_dir + "/ssl/vagrant.key")

    chef.json = deploy_ssl

    chef.log_level = :debug
  end
end
