name 'service'
maintainer 'Till Klampaeckel'
maintainer_email 'till@php.net'
license 'BSD-2-Clause'
description 'Role recipes for the service stack'

depends 'easybib'
depends 'loggly'
depends 'gearmand'
depends 'rabbitmq'
depends 'statsd'
depends 'nodejs'
