name              "getcourse"
maintainer        "Till Klampaeckel"
maintainer_email  "till@php.net"
license           "BSD License"
description       "getcourse roles"
version           "0.1"

supports 'ubuntu'

depends "easybib"
depends "nginx-app"
depends "getcourse-deploy"
depends "php-posix"
depends "php-zip"
depends "php-intl"
depends "php-gearman"
depends "php-mysqli"
depends "bash"
depends "snooze"
depends "percona"
depends "php-xdebug"
depends "avahi"
depends "nodejs"
depends "zsh"
depends "redis"
depends "memcache"
