this_dir = File.dirname(__FILE__)
require "#{File.dirname(this_dir)}/vagrant-test-library"

vagrant_test_config = get_setup_json

Vagrant::Config.run do |config|

  bibconfig = Bib::Vagrant::Config.new
  vagrantconfig = bibconfig.get

  config.vm.boot_mode = vagrantconfig['gui']
  config.vm.box = vagrant_test_config['box_file']

  config.vm.network :hostonly, vagrant_test_config['box_ip']

    config.vm.customize [
      "modifyvm", :id,
      "--name", vagrant_test_config['box_name'],
    ]

  config.vm.provision :shell, :inline => "sudo apt-spy2 fix --launchpad --country=#{get_country} --commit"
  config.vm.provision :shell, :inline => "sudo apt-get update"

  config.vm.provision :shell, :inline => "apt-get update -y"
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "./../../"
    chef.add_recipe "postfix"
    chef.add_recipe "postfix::relay"

    chef.log_level = vagrantconfig['chef_log_level']
  end
end
