name              'stack-scholar'
maintainer        'Till Klampaeckel'
maintainer_email  'till@php.net'
license           'BSD License'
description       'Scholar Stack'
version           '0.1'
source_url        'https://github.com/till/easybib-cookbooks' if respond_to?(:source_url)
issues_url        'https://github.com/till/easybib-cookbooks/issues' if respond_to?(:issues_url)

supports 'ubuntu'

depends 'nginx-app'
depends 'easybib-deploy'
depends 'ies-mysql'
depends 'redis'
depends 'memcache'
depends 'haproxy'
depends 'ohai'
depends 'apache-couchdb'
depends 'nodejs'
depends 'php'
depends 'php-fpm'
depends 'rsyslogd'
depends 'stack-service'
depends 'supervisor'
depends 'ies'
depends 'ies-letsencrypt'
depends 'ies-ssl'
