name              'stack-scholar'
maintainer        'Till Klampaeckel'
maintainer_email  'till@php.net'
license           'BSD License'
description       'Scholar Stack'
version           '0.1'

supports 'ubuntu'

depends 'nginx-app'
depends 'easybib-deploy'
depends 'ies-mysql'
depends 'redis'
depends 'memcache'
depends 'haproxy'
depends 'ohai'
depends 'apache-couchdb'
depends 'nodejs'
depends 'php'
depends 'php-fpm'
depends 'rsyslogd'
depends 'stack-easybib'
depends 'stack-service'
depends 'supervisor'
depends 'ies'
