name              'stack-qa'
maintainer        'Till Klampaeckel'
maintainer_email  'till@php.net'
license           'BSD License'
description       'ops infrastructure roles'
version           '0.1'

supports 'ubuntu'

depends 'bash'
depends 'composer'
depends 'ies'
depends 'easybib-deploy'
depends 'easybib_vagrant'
depends 'ezproxy'
depends 'nginx-app'
depends 'nodejs'
depends 'php'
depends 'php-fpm'
depends 'sinopia'
depends 'sinopia-github'
depends 'supervisor'
depends 'vagrant'
