Vagrant::Config.run do |config|

  config.vm.boot_mode = :gui
  config.vm.box = "easybib-ubuntu-12.04.4_vbox-4.3.6_chef-11.4.4_0.1"

  config.vm.network :hostonly, "33.33.33.124"

    config.vm.customize [
        "modifyvm", :id,
        "--name", "Vagrant Cookbook Testbox",
        "--memory", "256"
    ]

  config.vm.provision :shell, :inline => "sudo apt-spy2 fix --launchpad --country=de --commit"
  config.vm.provision :shell, :inline => "sudo apt-get update"

  config.vm.provision :shell, :inline => "apt-get update -y"
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "./../../"
    chef.add_recipe "tsung"
    #chef.add_recipe "easybib::role-getcourse-api"
    #chef.add_recipe "nginx-app::cache"
    #chef.add_recipe "php-opcache"
    #chef.add_recipe "qafoo-profiler"
    chef.json = JSON.parse(File.read("./deploy.json"))

    chef.log_level = :debug
  end
end
