name              'snooze'
maintainer        'Till Klampaeckel'
maintainer_email  'till@php.net'
license           'BSD License'
description       'Installs the gem for snooze.io'
version           '0.1'
recipe            'snooze::default', 'Installs the gem'
supports 'ubuntu'
