default["php-fpm"] = {}
default["php-fpm"][:version] = '5.3.5'
default["php-fpm"][:checksum] = "8aaf20c95e91f25c5b6a591e5d6d61b9"
default["php-fpm"][:prefix] = "/usr/local"
default["php-fpm"][:logfile] = "/var/log/php/error.log"
default["php-fpm"][:slowlog] = "/var/log/php/slow.log"
default["php-fpm"][:fpmlog] = "/var/log/php/fpm.log"
default["php-fpm"][:displayerrors] = false
default["php-fpm"][:logerrors] = true
default["php-fpm"][:maxexecutiontime] = 60
default["php-fpm"][:memorylimit] = "512M"
default["php-fpm"][:user] = "www-data"
default["php-fpm"][:group] = "www-data"
default["php-fpm"][:tmpdir] = "/tmp/php"
default["php-fpm"][:socketdir] = "/tmp/fpm-sockets"
default["php-fpm"][:apc_version] = "3.1.4"
default["php-fpm"][:xhprof_version] = "0.9.2"
default["php-fpm"][:source] = "easybib" # source, ubuntu, easybib
