name 'stack-wpt'

license 'Apache-2.0'

depends 'ark'
depends 'fake-sqs'
depends 'fake-s3'
depends 'ies-mysql'
depends 'java'
depends 'nginx-app'
depends 'nodejs'
depends 'ohai'
depends 'php'
depends 'stack-scholar'
depends 'supervisor'
