name 'stack-wpt'
maintainer 'Till Klampaeckel'
maintainer_email 'till@php.net'
license 'Apache-2.0'
source_url        'https://github.com/till/easybib-cookbooks' if respond_to?(:source_url)
issues_url        'https://github.com/till/easybib-cookbooks/issues' if respond_to?(:issues_url)
version           '0.1'
depends 'ark'
depends 'fake-sqs'
depends 'fake-s3'
depends 'ies-mysql'
depends 'java'
depends 'nginx-app'
depends 'nodejs'
depends 'ohai'
depends 'php'
depends 'redis'
depends 'stack-scholar'
depends 'supervisor'
