Vagrant::Config.run do |config|
  config.vm.box = "jenkins"
  config.vm.forward_port "http", 8080, 8080
  config.vm.provision :chef_solo do |chef|
     chef.cookbooks_path = "cookbooks"
  	 chef.add_recipe("vagrant_main") 
#  	 chef.add_recipe("jenkins") 
#  	 chef.add_recipe("jenkins::php-pear") 
  	 chef.add_recipe("jenkins::buildconfigs") 
  end 
end
