name              'stack-cmbm'
maintainer        'Till Klampaeckel'
maintainer_email  'till@php.net'
license           'BSD License'
description       'CitationMachine and BibMe Roles'
version           '0.1'

supports 'ubuntu'

depends 'ark'
depends 'easybib'
depends 'ies'
depends 'ies-mysql'
depends 'nginx-app'
depends 'supervisor'
