name              'stack-cmbm'
maintainer        'Brian Wiborg'
maintainer_email  'brian.wiborg@imagineeasy.com'
license           'BSD 2-clause'
description       'CitationMachine and BibMe Roles'
version           '0.1'

supports 'ubuntu'

depends 'easybib'
depends 'easybib-deploy'
depends 'haproxy'
depends 'ies'
depends 'ies-mysql'
depends 'ies-ruby'
depends 'ies-zsh'
depends 'nginx-app'
depends 'nodejs'
depends 'redis'
depends 'supervisor'
