#!/usr/local/bin/ruby

# curl options, in order
# HTTP method
# output file
# follow redirects
# response output
# http basic auth credentials
# post data
# show error
# silent

# add a node, username must have admin privs
# curl -X POST \
#      -o /dev/null \
#      -L \
#      -w \"%{http_code}\" \
#      -u foo:bar \
#      -d ip=8.8.8.8 \
#      -d input_id=0 \
#      -d name=test1 \
#      -S -s \
#      https://site.loggly.com/api/devices/
#
# delete a node
# curl -X DELETE /
#      -o /dev/null /
#      -L /
#      -w \"%{http_code}\" /
#      -u foo:bar \
#      -S -s \
#      https://site.loggly.com/api/devices/<id>

require 'rubygems'
require 'net/http'
require 'json'

username = ARGV[0]
password = ARGV[1]
hostname = ARGV[2]
domain = ARGV[3]

# http://www.ruby-doc.org/stdlib-1.8.7/libdoc/net/http/rdoc/Net/HTTP.html
uri = URI.parse("http://#{domain}.loggly.com/api/devices/")

Net::HTTP.start(uri.host) {|http|
  req = Net::HTTP::Get.new(uri.path)
  req.basic_auth username, password
  response = http.request(req)

  data = response.body
  result = JSON.parse(data)

  c = ""
  result.each do |i|
    if i["name"] == hostname 
      c = i["id"]
      break
    end
  end
  if c.size == 0
    puts "no such host: #{hostname}"
    exit 1
  else
    puts c
  end
}
