include_recipe 'easybib::setup'
include_recipe 'loggly::setup'
include_recipe 'rsyslogd::mute-cron'
include_recipe 'easybib-deploy::ssl-certificates'
include_recipe 'haproxy'
include_recipe 'haproxy::ctl'
