require 'json'
vagrant_test_config = JSON.parse(File.read('./../setup.json'))

Vagrant::Config.run do |config|

    bibconfig = Bib::Vagrant::Config.new
    vagrantconfig = bibconfig.get

    config.vm.boot_mode = vagrantconfig['gui']
    config.vm.box = vagrant_test_config['box_file']

    config.vm.network :hostonly, vagrant_test_config['box_ip']

    config.vm.customize [
        "modifyvm", :id,
        "--name", vagrant_test_config['box_name'],
        "--memory", vagrant_test_config['box_memory']
    ]

    config.vm.provision :shell, :inline => "apt-get update -y"

    config.vm.provision :chef_solo do |chef|
        chef.cookbooks_path = "./../../"
        chef.log_level = :debug
        chef.add_recipe "easybib::setup"
        chef.add_recipe "percona::server"
        chef.add_recipe "prosody"
        chef.json = JSON.parse(File.read("./prosody.json"))
    end
end
