name              'stack-easybib'
maintainer        'Till Klampaeckel'
maintainer_email  'till@php.net'
license           'BSD License'
description       'API roles'
version           '0.1'

supports 'ubuntu'

depends 'composer'
depends 'easybib'
depends 'easybib-deploy'
depends 'haproxy'
depends 'ies'
depends 'nginx-lb'
depends 'nginx-app'
depends 'memcache'
depends 'pecl-manager'
depends 'php'
depends 'php-fpm'
depends 'php-pear'
depends 'postfix'
depends 'redis'
depends 'tideways'
