AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
  Exclude:
    - vendor/**

ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
SignalException:
  Enabled: false
WordArray:
  Enabled: false
#
# These were needed to pass since I did not want to rewrite 
# Package clouds cookbook entirely I do not know the ramifications
# of having this exception but I am sure to be educated.
# -Joel
#
SingleLineBlockParams:
  Enabled: false
IdenticalConditionalBranches:
  Enabled: false
PredicateName:
  Enabled: false
TrailingCommaInArguments:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
