ENV['recipe_runlist'] = 'easybib::setup,ezproxy::server,ohai,avahi,avahi::alias,avahi::alias-service'
ENV['chef_json'] = "#{File.dirname(__FILE__)}/dna.json"

require_relative '../vagrant-provision'

this_dir = File.dirname(__FILE__)
require "#{File.dirname(this_dir)}/vagrant-test-library"
