name              'php'
maintainer        'Till Klampaeckel'
maintainer_email  'till@php.net'
version           '0.1'
license           'BSD License'
supports          'ubuntu'

depends 'ies-apt'
depends 'php-fpm'
depends 'ohai'
