name              'ies'
maintainer        'Till Klampaeckel'
maintainer_email  'till@php.net'
license           'BSD License'
description       'Our generic setup and install scripts across all stacks'
version           '0.1'
recipe            'ies::role-generic', 'Generic setup for all our instances'
recipe            'ies::setup-sns', 'Set up SNS notifications for our instances'
source_url        'https://github.com/till/easybib-cookbooks' if respond_to?(:source_url)
issues_url        'https://github.com/till/easybib-cookbooks/issues' if respond_to?(:issues_url)

supports 'ubuntu'

depends 'apt'
depends 'chef_handler_sns'
depends 'composer'
depends 'easybib'
depends 'fail2ban'
depends 'ies-route53'
depends 'monit'
depends 'nginx-app'
depends 'papertrail'
depends 'php'
depends 'php-fpm'
depends 'postfix'
depends 'rsyslogd'
depends 'tideways'
