maintainer        "Till Klampaeckel"
maintainer_email  "till@php.net"
license           "PHP License"
description       "Munin-Node and plugin setup"
version           "0.1"
recipe            "munin-node::setup",     "Install munin-node"
recipe            "munin-node::configure", "Node-specific configuration for munin-node on scalarium"
recipe            "munin-node::nginx",     "Enable plugins for nginx monitoring"
recipe            "munin-node::phpfpm",    "Enable plugins for php-fpm monitoring"
recipe            "munin-node::service",   "Internally used by other recipies"
recipe            "munin-node::redis",     "Enable plugin for redis"
supports 'ubuntu'
